const languages = [
  { value: "1c", label: "1C", extension: "1c" },
  { value: "4d", label: "4D", extension: "4d" },
  { value: "abap", label: "ABAP", extension: "abap" },
  { value: "abnf", label: "ABNF", extension: "abnf" },
  { value: "accesslog", label: "Access logs", extension: "" },
  { value: "ada", label: "Ada", extension: "adb" },
  { value: "arduino", label: "Arduino (C++ w/Arduino libs)", extension: "ino" },
  { value: "armasm", label: "ARM assembler", extension: "s" },
  { value: "avrasm", label: "AVR assembler", extension: "s" },
  { value: "actionscript", label: "ActionScript", extension: "as" },
  { value: "alan", label: "Alan IF", extension: "i" },
  { value: "angelscript", label: "AngelScript", extension: "asc" },
  { value: "apache", label: "Apache", extension: "conf" },
  { value: "applescript", label: "AppleScript", extension: "applescript" },
  { value: "arcade", label: "Arcade", extension: "py" },
  { value: "asciidoc", label: "AsciiDoc", extension: "adoc" },
  { value: "aspectj", label: "AspectJ", extension: "aj" },
  { value: "autohotkey", label: "AutoHotkey", extension: "ahk" },
  { value: "autoit", label: "AutoIt", extension: "au3" },
  { value: "awk", label: "Awk", extension: "awk" },
  { value: "ballerina", label: "Ballerina", extension: "bal" },
  { value: "bash", label: "Bash", extension: "sh" },
  { value: "basic", label: "Basic", extension: "bas" },
  { value: "bbcode", label: "BBCode", extension: "bbcode" },
  { value: "blade", label: "Blade (Laravel)", extension: "blade.php" },
  { value: "bnf", label: "BNF", extension: "bnf" },
  { value: "bqn", label: "BQN", extension: "bqn" },
  { value: "brainfuck", label: "Brainfuck", extension: "bf" },
  { value: "csharp", label: "C#", extension: "cs" },
  { value: "cpp", label: "C++", extension: "cpp" },
  { value: "c", label: "C", extension: "c" },
  { value: "cal", label: "C/AL", extension: "cal" },
  { value: "c3", label: "C3", extension: "c3" },
  { value: "cos", label: "Cache Object Script", extension: "cls" },
  { value: "candid", label: "Candid", extension: "did" },
  { value: "cmake", label: "CMake", extension: "cmake" },
  { value: "cobol", label: "COBOL", extension: "cob" },
  { value: "coq", label: "Coq", extension: "v" },
  { value: "csp", label: "CSP", extension: "csp" },
  { value: "css", label: "CSS", extension: "css" },
  { value: "capnproto", label: "Cap’n Proto", extension: "capnp" },
  { value: "chaos", label: "Chaos", extension: "kaos" },
  { value: "chapel", label: "Chapel", extension: "chpl" },
  { value: "cisco", label: "Cisco CLI", extension: "cfg" },
  { value: "clojure", label: "Clojure", extension: "clj" },
  { value: "coffeescript", label: "CoffeeScript", extension: "coffee" },
  { value: "cpcdos", label: "CpcdosC+", extension: "cpc" },
  { value: "crmsh", label: "Crmsh", extension: "crm" },
  { value: "crystal", label: "Crystal", extension: "cr" },
  { value: "curl", label: "cURL", extension: "sh" },
  { value: "cypher", label: "Cypher (Neo4j)", extension: "cypher" },
  { value: "dafny", label: "Dafny", extension: "dfy" },
  { value: "dart", label: "Dart", extension: "dart" },
  { value: "delphi", label: "Delphi", extension: "dpr" },
  { value: "diff", label: "Diff", extension: "diff" },
  { value: "django", label: "Django", extension: "html" },
  { value: "dns", label: "DNS Zone file", extension: "zone" },
  { value: "dockerfile", label: "Dockerfile", extension: "Dockerfile" },
  { value: "bat", label: "DOS (bat)", extension: "bat" },
  { value: "cmd", label: "DOS (cmd)", extension: "cmd" },
  { value: "dsconfig", label: "dsconfig", extension: "cfg" },
  { value: "dts", label: "DTS (Device Tree)", extension: "dts" },
  { value: "dust", label: "Dust", extension: "dust" },
  { value: "dylan", label: "Dylan", extension: "dyl" },
  { value: "ebnf", label: "EBNF", extension: "ebnf" },
  { value: "elixir", label: "Elixir", extension: "ex" },
  { value: "elm", label: "Elm", extension: "elm" },
  { value: "erlang", label: "Erlang", extension: "erl" },
  { value: "excel", label: "Excel", extension: "xlsx" },
  { value: "extempore", label: "Extempore", extension: "xtm" },
  { value: "fsharp", label: "F#", extension: "fs" },
  { value: "fix", label: "FIX", extension: "fix" },
  { value: "flix", label: "Flix", extension: "flix" },
  { value: "fortran", label: "Fortran", extension: "f90" },
  { value: "func", label: "FunC", extension: "func" },
  { value: "gcode", label: "G-Code", extension: "nc" },
  { value: "gams", label: "Gams", extension: "gms" },
  { value: "gauss", label: "GAUSS", extension: "gss" },
  { value: "gdscript", label: "GDScript", extension: "gd" },
  { value: "gherkin", label: "Gherkin", extension: "feature" },
  { value: "glimmer", label: "Glimmer and EmberJS", extension: "hbs" },
  { value: "gn", label: "GN for Ninja", extension: "gn" },
  { value: "go", label: "Go", extension: "go" },
  { value: "gf", label: "Grammatical Framework", extension: "gf" },
  { value: "golo", label: "Golo", extension: "golo" },
  { value: "gradle", label: "Gradle", extension: "gradle" },
  { value: "graphql", label: "GraphQL", extension: "graphql" },
  { value: "groovy", label: "Groovy", extension: "groovy" },
  { value: "gsql", label: "GSQL", extension: "gsql" },
  { value: "html", label: "HTML", extension: "html" },
  { value: "xml", label: "XML", extension: "xml" },
  { value: "http", label: "HTTP", extension: "" },
  { value: "haml", label: "Haml", extension: "haml" },
  { value: "handlebars", label: "Handlebars", extension: "hbs" },
  { value: "haskell", label: "Haskell", extension: "hs" },
  { value: "haxe", label: "Haxe", extension: "hx" },
  { value: "hlsl", label: "High-level shader language", extension: "hlsl" },
  { value: "hy", label: "Hy", extension: "hy" },
  { value: "ini", label: "Ini", extension: "ini" },
  { value: "toml", label: "TOML", extension: "toml" },
  { value: "inform7", label: "Inform7", extension: "i7" },
  { value: "irpf90", label: "IRPF90", extension: "f90" },
  { value: "iptables", label: "Iptables", extension: "rules" },
  { value: "json", label: "JSON", extension: "json" },
  { value: "java", label: "Java", extension: "java" },
  { value: "javascript", label: "JavaScript", extension: "js" },
  { value: "jolie", label: "Jolie", extension: "iol" },
  { value: "julia", label: "Julia", extension: "jl" },
  { value: "julia-repl", label: "Julia REPL", extension: "" },
  { value: "kotlin", label: "Kotlin", extension: "kt" },
  { value: "latex", label: "LaTeX", extension: "tex" },
  { value: "leaf", label: "Leaf", extension: "leaf" },
  { value: "lean", label: "Lean", extension: "lean" },
  { value: "lasso", label: "Lasso", extension: "lasso" },
  { value: "less", label: "Less", extension: "less" },
  { value: "ldif", label: "LDIF", extension: "ldif" },
  { value: "lisp", label: "Lisp", extension: "lisp" },
  { value: "livecodeserver", label: "LiveCode Server", extension: "server" },
  { value: "livescript", label: "LiveScript", extension: "ls" },
  { value: "lookml", label: "LookML", extension: "lkml" },
  { value: "lua", label: "Lua", extension: "lua" },
  { value: "macaulay2", label: "Macaulay2", extension: "m2" },
  { value: "makefile", label: "Makefile", extension: "Makefile" },
  { value: "markdown", label: "Markdown", extension: "md" },
  { value: "mathematica", label: "Mathematica", extension: "nb" },
  { value: "matlab", label: "Matlab", extension: "m" },
  { value: "maxima", label: "Maxima", extension: "mac" },
  { value: "mel", label: "Maya Embedded Language", extension: "mel" },
  { value: "mercury", label: "Mercury", extension: "m" },
  { value: "mips", label: "MIPS Assembler", extension: "asm" },
  { value: "mint", label: "Mint", extension: "mint" },
  { value: "mirc", label: "mIRC Scripting Language", extension: "mrc" },
  { value: "mizar", label: "Mizar", extension: "miz" },
  { value: "mkb", label: "MKB", extension: "mkb" },
  { value: "mlir", label: "MLIR", extension: "mlir" },
  { value: "mojolicious", label: "Mojolicious", extension: "mojo" },
  { value: "monkey", label: "Monkey", extension: "monkey" },
  { value: "moonscript", label: "Moonscript", extension: "moon" },
  { value: "motoko", label: "Motoko", extension: "mo" },
  { value: "n1ql", label: "N1QL", extension: "n1ql" },
  { value: "nsis", label: "NSIS", extension: "nsi" },
  { value: "never", label: "Never", extension: "nv" },
  { value: "nginx", label: "Nginx", extension: "conf" },
  { value: "nim", label: "Nim", extension: "nim" },
  { value: "nix", label: "Nix", extension: "nix" },
  { value: "oak", label: "Oak", extension: "oak" },
  { value: "ocl", label: "Object Constraint Language", extension: "ocl" },
  { value: "ocaml", label: "OCaml", extension: "ml" },
  { value: "objective-c", label: "Objective C (.m)", extension: "m" },
  { value: "mm", label: "Objective C (.mm)", extension: "mm" },
  { value: "glsl", label: "OpenGL Shading Language", extension: "glsl" },
  { value: "openscad", label: "OpenSCAD", extension: "scad" },
  {
    value: "ruleslanguage",
    label: "Oracle Rules Language",
    extension: "rules",
  },
  { value: "oxygene", label: "Oxygene", extension: "oxygene" },
  { value: "pf", label: "PF", extension: "conf" },
  { value: "php", label: "PHP", extension: "php" },
  { value: "papyrus", label: "Papyrus", extension: "psc" },
  { value: "parser3", label: "Parser3", extension: "parser3" },
  { value: "pl", label: "Perl (.pl)", extension: "pl" },
  { value: "pm", label: "Perl (.pm)", extension: "pm" },
  { value: "pine", label: "Pine Script", extension: "pinescript" },
  { value: "plain", label: "Plain Text", extension: "txt" },
  { value: "pony", label: "Pony", extension: "pony" },
  { value: "postgresql", label: "PostgreSQL", extension: "sql" },
  { value: "pgsql", label: "PL/pgSQL", extension: "sql" },
  { value: "powershell", label: "PowerShell", extension: "ps1" },
  { value: "processing", label: "Processing", extension: "pde" },
  { value: "prolog", label: "Prolog", extension: "pl" },
  { value: "properties", label: "Properties", extension: "properties" },
  { value: "protobuf", label: "Protocol Buffers", extension: "proto" },
  { value: "puppet", label: "Puppet", extension: "pp" },
  { value: "python", label: "Python", extension: "py" },
  { value: "profile", label: "Python profiler results", extension: "prof" },
  { value: "python-repl", label: "Python REPL", extension: "" },
  { value: "qsharp", label: "Q#", extension: "qs" },
  { value: "k", label: "Q", extension: "q" },
  { value: "qml", label: "QML", extension: "qml" },
  { value: "r", label: "R", extension: "r" },
  { value: "razor", label: "Razor CSHTML", extension: "cshtml" },
  { value: "reasonml", label: "ReasonML", extension: "re" },
  { value: "redbol", label: "Rebol", extension: "reb" },
  { value: "red", label: "Red", extension: "red" },
  { value: "rib", label: "RenderMan RIB", extension: "rib" },
  { value: "rsl", label: "RenderMan RSL", extension: "sl" },
  { value: "riscript", label: "RiScript", extension: "ris" },
  { value: "riscvasm", label: "RISC-V Assembly", extension: "asm" },
  { value: "roboconf", label: "Roboconf (.instances)", extension: "instances" },
  { value: "graph", label: "Roboconf (.graph)", extension: "graph" },
  { value: "robot", label: "Robot Framework", extension: "robot" },
  { value: "rpm-specfile", label: "RPM spec files", extension: "spec" },
  { value: "ruby", label: "Ruby", extension: "rb" },
  { value: "rust", label: "Rust", extension: "rs" },
  { value: "rvt-script", label: "RVT Script", extension: "rvt" },
  { value: "sas", label: "SAS", extension: "sas" },
  { value: "scss", label: "SCSS", extension: "scss" },
  { value: "sql", label: "SQL", extension: "sql" },
  { value: "step21", label: "STEP Part 21", extension: "stp" },
  { value: "scala", label: "Scala", extension: "scala" },
  { value: "scheme", label: "Scheme", extension: "scm" },
  { value: "scilab", label: "Scilab", extension: "sci" },
  { value: "sfz", label: "SFZ", extension: "sfz" },
  { value: "shexc", label: "Shape Expressions", extension: "shex" },
  { value: "shell", label: "Shell", extension: "sh" },
  { value: "smali", label: "Smali", extension: "smali" },
  { value: "smalltalk", label: "Smalltalk", extension: "st" },
  { value: "sml", label: "SML", extension: "sml" },
  { value: "solidity", label: "Solidity", extension: "sol" },
  { value: "splunk-spl", label: "Splunk SPL", extension: "spl" },
  { value: "stan", label: "Stan", extension: "stan" },
  { value: "stata", label: "Stata", extension: "do" },
  { value: "structured-text", label: "Structured Text", extension: "st" },
  { value: "stylus", label: "Stylus", extension: "styl" },
  { value: "subunit", label: "SubUnit", extension: "sub" },
  { value: "supercollider", label: "Supercollider", extension: "sc" },
  { value: "svelte", label: "Svelte", extension: "svelte" },
  { value: "swift", label: "Swift", extension: "swift" },
  { value: "tcl", label: "Tcl", extension: "tcl" },
  { value: "terraform", label: "Terraform (HCL)", extension: "tf" },
  { value: "tap", label: "Test Anything Protocol", extension: "tap" },
  { value: "thrift", label: "Thrift", extension: "thrift" },
  { value: "toit", label: "Toit", extension: "toit" },
  { value: "tp", label: "TP", extension: "tp" },
  { value: "tsql", label: "Transact-SQL", extension: "sql" },
  { value: "twig", label: "Twig", extension: "twig" },
  { value: "typescript", label: "TypeScript", extension: "ts" },
  { value: "unicorn-rails-log", label: "Unicorn Rails log", extension: "log" },
  { value: "vbnet", label: "VB.Net", extension: "vb" },
  { value: "vba", label: "VBA", extension: "vba" },
  { value: "vbscript", label: "VBScript", extension: "vbs" },
  { value: "vhdl", label: "VHDL", extension: "vhd" },
  { value: "vala", label: "Vala", extension: "vala" },
  { value: "verilog", label: "Verilog", extension: "v" },
  { value: "vim", label: "Vim Script", extension: "vim" },
  { value: "xsharp", label: "X#", extension: "xs" },
  { value: "xpp", label: "X++", extension: "xpp" },
  { value: "x86asm", label: "x86 Assembly", extension: "asm" },
  { value: "x86asmatt", label: "x86 Assembly (AT&T)", extension: "s" },
  { value: "xl", label: "XL", extension: "xl" },
  { value: "xquery", label: "XQuery", extension: "xq" },
  { value: "yaml", label: "YAML (.yaml)", extension: "yaml" },
  { value: "yml", label: "YAML (.yml)", extension: "yml" },
  { value: "zenscript", label: "ZenScript", extension: "zs" },
  { value: "zephir", label: "Zephir", extension: "zep" },
];

export function getHighlightingLanguages() {
  return languages;
}

export function getLanguageExtention(language: string) {
  const lang = languages.find((lang) => lang.value === language);

  return lang ? lang.extension : "txt";
}
